<#
.SYNOPSIS
    Merges all per-user wiki/log/{user}/YYYY-MM-DD.md files into a single
    chronological timeline (read-only, not committed).
.DESCRIPTION
    Restores the grep-able single-log property from the Karpathy LLM Wiki
    pattern. Per-user logs prevent merge conflicts; this view recombines
    them for timeline review.

    Output entries are normalized to:
        ## [YYYY-MM-DD HH:MM] {user} | action | description

    so `grep "^## \[" merged-log.md | tail -20` works as in the original pattern.
.PARAMETER OutputPath
    Where to write the merged log. Defaults to wiki/.merged-log.md (gitignored
    by convention — add to .gitignore if not already excluded).
.PARAMETER Tail
    If set, print only the last N entries to stdout instead of writing a file.
.EXAMPLE
    .\merge-logs.ps1
    .\merge-logs.ps1 -Tail 20
#>
param(
    [string]$OutputPath,
    [int]$Tail = 0
)

$wikiRoot = (Resolve-Path (Join-Path $PSScriptRoot ".." "wiki")).Path
$logRoot = Join-Path $wikiRoot "log"

if (-not (Test-Path $logRoot)) {
    Write-Error "Log root not found: $logRoot"
    exit 1
}

# Collect every per-user daily log
$logFiles = Get-ChildItem -Path $logRoot -Recurse -Filter "*.md" |
    Where-Object { $_.Name -match "^\d{4}-\d{2}-\d{2}\.md$" }

$entries = New-Object System.Collections.Generic.List[object]

foreach ($file in $logFiles) {
    $date = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
    $user = Split-Path (Split-Path $file.FullName -Parent) -Leaf
    $content = Get-Content $file.FullName

    foreach ($line in $content) {
        # Match: ## [HH:MM] action | description
        if ($line -match '^##\s+\[(\d{2}:\d{2})\]\s+(.+)$') {
            $time = $matches[1]
            $rest = $matches[2]
            $entries.Add([pscustomobject]@{
                Timestamp = "$date $time"
                User      = $user
                Body      = $rest
            }) | Out-Null
        }
    }
}

$sorted = $entries | Sort-Object Timestamp

if ($Tail -gt 0) {
    $sorted = $sorted | Select-Object -Last $Tail
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("# Merged Operation Log") | Out-Null
$lines.Add("") | Out-Null
$lines.Add("> Auto-generated by ``scripts/merge-logs.ps1``. Read-only — do NOT commit.") | Out-Null
$lines.Add("> Source: ``wiki/log/{user}/YYYY-MM-DD.md`` per-user files.") | Out-Null
$lines.Add("> Grep: ``Select-String '^## \[' .merged-log.md | Select-Object -Last 20``") | Out-Null
$lines.Add("") | Out-Null
$lines.Add("Total entries: $($sorted.Count)") | Out-Null
$lines.Add("") | Out-Null

foreach ($e in $sorted) {
    $lines.Add("## [$($e.Timestamp)] $($e.User) | $($e.Body)") | Out-Null
}

$output = $lines -join "`r`n"

if ($Tail -gt 0 -and -not $OutputPath) {
    Write-Output $output
} else {
    if (-not $OutputPath) {
        $OutputPath = Join-Path $wikiRoot ".merged-log.md"
    }
    Set-Content -Path $OutputPath -Value $output -Encoding UTF8
    Write-Host "Merged $($sorted.Count) entries from $($logFiles.Count) files -> $OutputPath"
}
